services:
  bookmark-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - stash-app:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped

volumes:
  stash-data:
