version: '3.8'

services:
  bookmark-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reloading
      - ./backend:/app/backend:ro
      - ./frontend-react/src:/app/frontend-react/src:ro
      - ./frontend-react/public:/app/frontend-react/public:ro
      - ./frontend-react/package.json:/app/frontend-react/package.json:ro
      - ./frontend-react/vite.config.js:/app/frontend-react/vite.config.js:ro
      # Persistent data
      - bookmark-data:/app/data
      # Node modules (don't mount these)
      - /app/backend/node_modules
      - /app/frontend-react/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    restart: unless-stopped

volumes:
  bookmark-data: